### ISSUE TITLE
[Admin] Low priority : Can't move apps back to pending after they've been moved to interviewed/rejected/etc

### ISSUE THREAD

**Issue by luisasanmartin** [uwblueprint/website#32] opened 2017-03-13 02:13 UTC

**Comment by bryanc208** [comment] 2017-03-14 03:38
This is by design. Pending is a state to indicate that no one has touched the application in any way. It wouldn't make sense to be able to switch it back to this state since it would contradict its meaning. Closing.

**Closed by bryanc208** 2017-03-14 03:38 UTC
