### ISSUE TITLE
[Task] Investigate why no resume links are showing for any candidates

### ISSUE THREAD

**Issue by luisasanmartin** [uwblueprint/website#68] opened 2017-03-31 07:03 UTC
I suspect at least some of the new candidates provided a link to their resume.

**Comment by bryanc208** [comment] 2017-03-31 07:10
We just recently removed resume links for people that do not provide resumes. No other code change has been made that should affect this. Let's close this until it can be verified.

**Comment by hkjayakumar** [comment] 2017-03-31 22:25
However unlikely, this was probably just by chance, since I was able to successfully upload a resume while resolving #66

**Comment by chrisjluc** [comment] 2017-04-05 02:37
@bryanc208  I've submitted a test application with a resume (pdf, jpg), and it did not show up in prod. The application shows up but it's missing the resume.

Follow up, have we lost these resumes?

**Comment by hkjayakumar** [comment] 2017-04-05 02:40
Issue is probably related to auth. Resumes are uploaded when logged in as admin using @uwblueprint.org accounts, but are not uploaded when in incognito or without admin access

**Comment by chrisjluc** [comment] 2017-04-05 02:43
Uploading requires user to be authenticated it appears.
<img width="946" alt="screen shot 2017-04-04 at 7 42 42 pm" src="https://cloud.githubusercontent.com/assets/5094088/24687524/ec241f0a-196e-11e7-9ba9-a107ead78c4a.png">

**Comment by hkjayakumar** [comment] 2017-04-05 02:46
The dev website does not require auth for upload. The initial applications had the resumes attached since they were pointing to the dev db. The dev and prod dbs were separated and we don't have any resumes since then.

This is also why the initial testing on the dev website went well, and this issue was closed.

**Comment by chrisjluc** [comment] 2017-04-05 02:47
I changed the rules to allow anybody to read or write. And uploading a file now works.

Is this a viable long term solution?

**Comment by chrisjluc** [comment] 2017-04-05 02:48
Looks like we lost those 16 resumes, so we may need to contact them directly.

Can somebody confirm?

**Comment by chrisjluc** [comment] 2017-04-05 03:05
It's confirmed that uploading resume now works: https://www.uwblueprint.org/admin/student-details/-Kgw3VpXq-hf4haC_lo3

**Comment by chrisjluc** [comment] 2017-04-05 03:05
It's confirmed that uploading resumes now works with the most recent applicant, Ankita.

**Comment by aaronte** [comment] 2017-04-05 04:22
@chrisjluc Yeah. Might have to contact those people that have lost resumes. Can't think of a way to recover those.

**Comment by bryanc208** [comment] 2017-04-05 05:49
Not sure why the storage rules have become restricted. I could have sworn they were set to allow all when we launched. Either way, now that the issue is fixed let's close this bug and further discuss in Slack.

**Closed by bryanc208** 2017-04-05 05:49 UTC
Labels: bug, high priority
